## [예제] 미국 대통령 당선 정보에서 정당 정보를 도출하여 시각하 하기


### * 불러온 데이타집합의 정보 확인하기

- type(df)  : 데이타 타입
- df.shape  : 행과 열의 수
- df.columns : 컬럼명 확인
- df.dtypes : 각각의 컬럼 데이타타입
- df.info() : df.dtypes 비슷
- df.info
- df.head()
- df.tail()


### 파이썬과 판다스 자료형 비교
    int         int64
    float       float64
    string      object(****)

###  당선된 각 정당(Political Party) 수를 먼저 구해야 한다

- value_counts() 이용

- 원그래프 출력


### [연습] 데이타셋에서 다른 인사이드를 도출하여 시각화하기

In [5]:
import pandas as pd
df = pd.read_excel('http://qrc.depaul.edu/excel_files/presidents.xlsx')
df

,President,Years in office,Year first inaugurated,Age at inauguration,State elected from,# of electoral votes,# of popular votes,National total votes,Total electoral votes,Rating points,Political Party,Occupation,College,% electoral,% popular
0,George Washington,8.0,1789,57,Virginia,69,NA(),NA(),69,842.0,None,Planter,None,100.000000,NA()
1,John Adams,4.0,1797,61,Massachusetts,132,NA(),NA(),139,598.0,Federalist,Lawyer,Harvard,94.964029,NA()
2,Thomas Jefferson,8.0,1801,57,Virginia,73,NA(),NA(),137,711.0,Democratic-Republican,"Planter, Lawyer",William and Mary,53.284672,NA()
3,James Madison,8.0,1809,57,Virginia,122,NA(),NA(),176,567.0,Democratic-Republican,Lawyer,Princeton,69.318182,NA()
4,James Monroe,8.0,1817,58,Virginia,183,NA(),NA(),221,602.0,Democratic-Republican,Lawyer,William and Mary,82.805430,NA()
5,John Quincy Adams,4.0,1825,57,Massachusetts,84,NA(),NA(),261,564.0,Democratic-Republican,Lawyer,Harvard,32.183908,NA()
6,Andrew Jackson,8.0,1829,61,Tennessee,178,642553,1148018,261,632.0,Democrat,Lawyer,None,68.199234,55.970638
7,Martin Van Buren,4.0,1837,54,New York,170,764176,1503534,294,429.0,Democrat,Lawyer,None,57.823129,50.825322
8,William Henry Harrison,0.8,1841,68,Ohio,234,1275390,2411808,294,329.0,Whig,Soldier,Hampden-Sydney,79.591837,52.881075
9,James K. Polk,4.0,1845,49,Tennessee,170,1339494,2703659,275,632.0,Democrat,Lawyer,U. of North Carolina,61.818182,49.543748
10,Zachary Taylor,1.0,1849,64,Louisiana,163,1361393,2879184,290,447.0,Whig,Soldier,None,56.206897,47.283987
11,Franklin Pierce,4.0,1853,48,New Hampshire,254,1607510,3161830,296,286.0,Democrat,Lawyer,Bowdoin,85.810811,50.841127
12,James Buchanan,4.0,1857,65,Pennsylvania,174,1836072,4054647,296,259.0,Democrat,Lawyer,Dickinson,58.783784,45.283153
13,Abraham Lincoln,4.0,1861,52,Illinois,180,1865908,4685561,303,900.0,Republican,Lawyer,None,59.405941,39.82251
14,Ulysses S. Grant,8.0,1869,46,Illinois,214,3013650,5722440,294,403.0,Republican,Soldier,US Military Academy,72.789116,52.663724
15,Rutherford B. Hayes,4.0,1877,54,Ohio,185,4034311,8413101,369,477.0,Republican,Lawyer,Kenyon,50.135501,47.952723
16,James A. Garfield,0.5,1881,49,Ohio,214,4446158,9210420,369,444.0,Republican,Lawyer,Williams,57.994580,48.27313
17,Grover Cleveland,4.0,1885,47,New York,219,4874621,10049754,401,576.0,Democrat,Lawyer,None,54.613466,48.504879
18,Benjamin Harrison,4.0,1889,55,Indiana,233,5443892,11383320,401,426.0,Republican,Lawyer,Miami,58.104738,47.823412
19,Grover Cleveland,4.0,1893,55,New York,277,5551883,12056097,444,576.0,Democrat,Lawyer,None,62.387387,46.050417
20,William McKinley,4.0,1897,54,Ohio,271,7108480,13935738,447,601.0,Republican,Lawyer,Allegheny College,60.626398,51.008996
21,William Howard Taft,4.0,1909,51,Ohio,321,7676258,14882734,483,491.0,Republican,Lawyer,Yale,66.459627,51.578279
22,Woodrow Wilson,8.0,1913,56,New Jersey,435,6293152,15040963,531,723.0,Democrat,Educator,Princeton,81.920904,41.840087
23,Warren G. Harding,2.0,1921,55,Ohio,404,16133314,26753786,531,326.0,Republican,Editor,None,76.082863,60.302919
24,Herbert Hoover,4.0,1929,54,California,444,21411991,36790364,531,400.0,Republican,Engineer,Stanford,83.615819,58.199998
25,Franklin Roosevelt,12.0,1933,51,New York,472,22825016,39749382,531,876.0,Democrat,Lawyer,Harvard,88.888889,57.422317
26,Dwight D. Eisenhower,8.0,1953,62,New York,442,33936137,61551118,531,699.0,Republican,Soldier,US Military Academy,83.239171,55.134883
27,John F. Kennedy,3.0,1961,43,Massachusetts,303,34221344,68828960,537,704.0,Democrat,Author,Harvard,56.424581,49.719397
28,Richard M. Nixon,5.0,1969,56,New York,301,31785148,73203370,538,477.0,Republican,Lawyer,Whittier,55.947955,43.420334
29,Jimmy Carter,4.0,1977,52,Georgia,297,40830763,81555889,538,518.0,Democrat,Businessman,US Naval Academy,55.204461,50.064764
30,Ronald Reagan,8.0,1981,69,California,489,43904153,86515221,538,634.0,Republican,Actor,Eureka College,90.892193,50.747316
31,George Bush,4.0,1989,64,Texas,426,48886097,91584820,538,548.0,Republican,Businessman,Yale,79.182156,53.377947
32,Bill Clinton,8.0,1993,46,Arkansas,370,44909326,104425014,538,539.0,Democrat,Lawyer,Georgetown,68.773234,43.006292
33,George W. Bush,8.0,2001,54,Texas,271,50460110,105417258,538,NaN,Republican,Businessman,Yale,50.371747,47.86703
34,Barack Obama,NaN,2009,47,Illinois,365,69492376,129438754,538,NaN,Democrat,Lawyer,Columbia University,67.843866,53.687457

In [ ]:
###  [참고] 웹에서 제공하는 데이타를 다운로드하기 

# import urllib.request as req

# local = './data/president/presidents.xlsx'  # data폴더 밑에 president 폴더가 있어야 한다
# url = 'http://qrc.depaul.edu/excel_files/presidents.xlsx'
# req.urlretrieve(url,local)
# print('다운로드 완료')

####  데이타 정보 확인하기

- print(type(df))  # 데이타 타입
- print(df.shape) # 행과 열의 수
- print(df.columns) # 컬럼명 확인
- print(df.dtypes) # 각각의 컬럼 데이타타입
- print(df.info()) # df.dtypes 비슷
- print(df.info) # 전체적인 내용을???
- print(df.head())
- print(df.tail())

### * 인사이트를 도출하여 정보를 추출하고 시각화

In [12]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [17]:
print(df.shape)

(35, 15)

In [18]:
print(df.columns)

Index(['President', 'Years in office', 'Year first inaugurated',
       'Age at inauguration', 'State elected from', '# of electoral votes',
       '# of popular votes', 'National total votes', 'Total electoral votes',
       'Rating points', 'Political Party', 'Occupation', 'College',
       '% electoral', '% popular'],
      dtype='object')

In [14]:
print(df.info)

<bound method DataFrame.info of                  President  Years in office  Year first inaugurated  \
0        George Washington              8.0                    1789
1               John Adams              4.0                    1797
2         Thomas Jefferson              8.0                    1801
3            James Madison              8.0                    1809
4             James Monroe              8.0                    1817
5        John Quincy Adams              4.0                    1825
6           Andrew Jackson              8.0                    1829
7        Martin Van Buren               4.0                    1837
8   William Henry Harrison              0.8                    1841
9            James K. Polk              4.0                    1845
10          Zachary Taylor              1.0                    1849
11         Franklin Pierce              4.0                    1853
12          James Buchanan              4.0                    1857
13         Abraham Lincoln              4.0                    1861
14        Ulysses S. Grant              8.0                    1869
15     Rutherford B. Hayes              4.0                    1877
16       James A. Garfield              0.5                    1881
17        Grover Cleveland              4.0                    1885
18       Benjamin Harrison              4.0                    1889
19        Grover Cleveland              4.0                    1893
20        William McKinley              4.0                    1897
21     William Howard Taft              4.0                    1909
22          Woodrow Wilson              8.0                    1913
23       Warren G. Harding              2.0                    1921
24          Herbert Hoover              4.0                    1929
25      Franklin Roosevelt             12.0                    1933
26    Dwight D. Eisenhower              8.0                    1953
27         John F. Kennedy              3.0                    1961
28        Richard M. Nixon              5.0                    1969
29            Jimmy Carter              4.0                    1977
30           Ronald Reagan              8.0                    1981
31             George Bush              4.0                    1989
32            Bill Clinton              8.0                    1993
33          George W. Bush              8.0                    2001
34            Barack Obama              NaN                    2009

    Age at inauguration State elected from  # of electoral votes  \
0                    57           Virginia                    69
1                    61      Massachusetts                   132
2                    57           Virginia                    73
3                    57           Virginia                   122
4                    58           Virginia                   183
5                    57      Massachusetts                    84
6                    61          Tennessee                   178
7                    54           New York                   170
8                    68               Ohio                   234
9                    49          Tennessee                   170
10                   64          Louisiana                   163
11                   48      New Hampshire                   254
12                   65       Pennsylvania                   174
13                   52           Illinois                   180
14                   46           Illinois                   214
15                   54               Ohio                   185
16                   49               Ohio                   214
17                   47           New York                   219
18                   55            Indiana                   233
19                   55           New York                   277
20                   54               Ohio                   271
21                   51               Ohio                   321
22                   56         New Jersey                   435
23                   55               Ohio                   404
24                   54         California                   444
25                   51           New York                   472
26                   62           New York                   442
27                   43      Massachusetts                   303
28                   56           New York                   301
29                   52            Georgia                   297
30                   69         California                   489
31                   64              Texas                   426
32                   46           Arkansas                   370
33                   54              Texas                   271
34                   47           Illinois                   365

   # of popular votes National total votes  Total electoral votes  \
0                NA()                 NA()                     69
1                NA()                 NA()                    139
2                NA()                 NA()                    137
3                NA()                 NA()                    176
4                NA()                 NA()                    221
5                NA()                 NA()                    261
6              642553              1148018                    261
7              764176              1503534                    294
8             1275390              2411808                    294
9             1339494              2703659                    275
10            1361393              2879184                    290
11            1607510              3161830                    296
12            1836072              4054647                    296
13            1865908              4685561                    303
14            3013650              5722440                    294
15            4034311              8413101                    369
16            4446158              9210420                    369
17            4874621             10049754                    401
18            5443892             11383320                    401
19            5551883             12056097                    444
20            7108480             13935738                    447
21            7676258             14882734                    483
22            6293152             15040963                    531
23           16133314             26753786                    531
24           21411991             36790364                    531
25           22825016             39749382                    531
26           33936137             61551118                    531
27           34221344             68828960                    537
28           31785148             73203370                    538
29           40830763             81555889                    538
30           43904153             86515221                    538
31           48886097             91584820                    538
32           44909326            104425014                    538
33           50460110            105417258                    538
34           69492376            129438754                    538

    Rating points        Political Party       Occupation  \
0           842.0                   None          Planter
1           598.0             Federalist           Lawyer
2           711.0  Democratic-Republican  Planter, Lawyer
3           567.0  Democratic-Republican           Lawyer
4           602.0  Democratic-Republican           Lawyer
5           564.0  Democratic-Republican           Lawyer
6           632.0               Democrat           Lawyer
7           429.0               Democrat           Lawyer
8           329.0                   Whig          Soldier
9           632.0               Democrat           Lawyer
10          447.0                   Whig          Soldier
11          286.0               Democrat           Lawyer
12          259.0               Democrat           Lawyer
13          900.0             Republican           Lawyer
14          403.0             Republican          Soldier
15          477.0             Republican           Lawyer
16          444.0             Republican           Lawyer
17          576.0               Democrat           Lawyer
18          426.0             Republican           Lawyer
19          576.0               Democrat           Lawyer
20          601.0             Republican           Lawyer
21          491.0             Republican           Lawyer
22          723.0               Democrat         Educator
23          326.0             Republican           Editor
24          400.0             Republican         Engineer
25          876.0               Democrat           Lawyer
26          699.0             Republican          Soldier
27          704.0               Democrat           Author
28          477.0             Republican           Lawyer
29          518.0               Democrat      Businessman
30          634.0             Republican            Actor
31          548.0             Republican      Businessman
32          539.0               Democrat           Lawyer
33            NaN             Republican      Businessman
34            NaN               Democrat           Lawyer

                 College  % electoral  % popular
0                   None   100.000000       NA()
1                Harvard    94.964029       NA()
2       William and Mary    53.284672       NA()
3              Princeton    69.318182       NA()
4       William and Mary    82.805430       NA()
5                Harvard    32.183908       NA()
6                   None    68.199234  55.970638
7                   None    57.823129  50.825322
8         Hampden-Sydney    79.591837  52.881075
9   U. of North Carolina    61.818182  49.543748
10                  None    56.206897  47.283987
11               Bowdoin    85.810811  50.841127
12             Dickinson    58.783784  45.283153
13                  None    59.405941   39.82251
14   US Military Academy    72.789116  52.663724
15                Kenyon    50.135501  47.952723
16              Williams    57.994580   48.27313
17                  None    54.613466  48.504879
18                 Miami    58.104738  47.823412
19                  None    62.387387  46.050417
20     Allegheny College    60.626398  51.008996
21                  Yale    66.459627  51.578279
22             Princeton    81.920904  41.840087
23                  None    76.082863  60.302919
24              Stanford    83.615819  58.199998
25               Harvard    88.888889  57.422317
26   US Military Academy    83.239171  55.134883
27               Harvard    56.424581  49.719397
28              Whittier    55.947955  43.420334
29      US Naval Academy    55.204461  50.064764
30        Eureka College    90.892193  50.747316
31                  Yale    79.182156  53.377947
32            Georgetown    68.773234  43.006292
33                  Yale    50.371747   47.86703
34   Columbia University    67.843866  53.687457  >

In [15]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   President               35 non-null     object
 1   Years in office         34 non-null     float64
 2   Year first inaugurated  35 non-null     int64
 3   Age at inauguration     35 non-null     int64
 4   State elected from      35 non-null     object
 5   # of electoral votes    35 non-null     int64
 6   # of popular votes      35 non-null     object
 7   National total votes    35 non-null     object
 8   Total electoral votes   35 non-null     int64
 9   Rating points           33 non-null     float64
 10  Political Party         35 non-null     object
 11  Occupation              35 non-null     object
 12  College                 35 non-null     object
 13  % electoral             35 non-null     float64
 14  % popular               35 non-null     object
dtypes: float64(3), int64(4), object(8)
memory usage: 4.2+ KB
None

In [16]:
print(df.dtypes)

President                  object
Years in office           float64
Year first inaugurated      int64
Age at inauguration         int64
State elected from         object
# of electoral votes        int64
# of popular votes         object
National total votes       object
Total electoral votes       int64
Rating points             float64
Political Party            object
Occupation                 object
College                    object
% electoral               float64
% popular                  object
dtype: object

In [21]:
value_counts()

NameError: name 'value_counts' is not defined